### ISSUE TITLE
Could you provide a portable version of CheckIP?

### ISSUE THREAD

**Issue by pstein** [valnoxy/checkip#12]
Could you provide a portable version of CheckIP?

I want to run it from USB flash drive

**Comment by valnoxy** [comment]
Hey, I've uploaded a portable version now. [See here](https://github.com/valnoxy/checkip/releases/tag/v2.3.0)

**Comment by pstein** [comment]
Thank you.
However I am confused.
The Portable version is 6 times (!) bigger than the installer version.
This cannot be.

Why not just zip the files from installation folder of installer version?
And thats it.
