### ISSUE TITLE
Here are a few suggestions for improvement if possible

### ISSUE THREAD

**Issue by ISensuiI** [valnoxy/checkip#2]
Hello, thank you for writing such a good software, I have been using it for a few days and it is very good.
I usually use vpn to surf the Internet, so I need to know whether my IP is correct every time I turn on the computer.

Here are a few suggestions for improvement if possible:

When minimized, the icon can be displayed on the tray. The icon can be replaced by the national flag icon, so that you can immediately know the current IP belongs to the region and country.
When you minimize to the tray, you can hover the mouse to display a prompt. The content of the prompt is the basic information, including the IP region and country. This avoids having to open it every time.
The IP can be refreshed. For example, if I change the IP in the middle, can it be automatically recognized, or give a refresh button, so that I only need to open the software once when I work for a long time.
https://vpntesting.com/my-ip-address The actual reference example can be seen here. I used this software before, but they seem to have stopped supporting it and can’t use it anymore.
Thank you for the work you do

**Comment by valnoxy** [comment]
Hey, thanks for your feedback! I like your idea, I will implement it soon.

**Comment by valnoxy** [comment]
Closed: Added in Version 2.2.0
