### ISSUE TITLE
It is really great.

### ISSUE THREAD

**Issue by ISensuiI** [valnoxy/checkip#4]
Hello friends, I have received the latest version and installed it.It is really great. I tried to donate just now, but my country does not support paypal, so there is no way to recharge. If you use WeChat, you can send a receipt I would like to send you 10$ to express my thanks.

**Comment by valnoxy** [comment]
Thank you, I appreciate it! Unfortunately I don't have WeChat, however I do have GitHub Sponsoring (https://github.com/sponsors/valnoxy) or BuyMeACoffee (https://buymeacoffee.com/valnoxy) as an alternative.
