### ISSUE TITLE
[BUG] Multilanguage GUI - Strings not translated 

### ISSUE THREAD

**Issue by bovirus** [valnoxy/checkip#7]
@valnoxy 

**Describe the bug**
I made teh changes to add italian language.
I compield it with VisualC++ 
Some strings seems not translated.
Some value ("false" or "true" are not translated)

**Screenshots**

![image](https://user-images.githubusercontent.com/1262554/226171132-c1165411-454c-4841-823e-879abe52658d.png)

The strings "false" / "Trues" are not localized

![image](https://user-images.githubusercontent.com/1262554/226171150-57120355-bd4a-423f-af46-c580707d91f8.png)

The window title "Info" should have a differnt strings then "info" in main UI (shoretr in main UI and longer in About window).
Library name author reuired tranlation ("by" -> "di"). Add these strings to language file.
tring that contain "All right rserved" reuqired translation. Add this string to language file.

**Device (please complete the following information):**
 - Windows Version: Windows 10 22H2
 - Device model: 
 - Device type (Desktop, Laptop...): Desktop HP 800 G1

**Additional context**

Please merge my italian language files.
Please fix the issue.

**Comment by valnoxy** [comment]
The strings you mentioned can now be localized, but I cannot separate the title on the page and navigation bar due to a limitation of WPF UI.
